name: vfmt

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: install-v
        run: |
          git clone https://github.com/vlang/v
          cd v
          make
          ./v -o v v.v
          sudo ./v symlink
          touch test.v
          echo "print('Hello')" > test.v
          cat test.v
          v run test.v
      - name: Format all v files in commit
        run: |
          ls
          cd day_2 && v fmt *.v
